# Используем официальный образ Python 3.12
FROM python:3.12.6-slim

# Устанавливаем рабочую директорию
WORKDIR /app

# Устанавливаем curl
RUN apt-get update && apt-get install -y curl && apt-get clean && rm -rf /var/lib/apt/lists/*

# Копируем файл с зависимостями
COPY requirements.txt .

# Устанавливаем зависимости
RUN pip install --no-cache-dir -r requirements.txt

# Копируем весь код проекта
COPY . .

# Запускаем админ-бота
CMD ["python", "admin_bot.py"]