services:
  # Сервис для админ-бота
  admin-bot:
    build:
      context: .  # Используем текущую директорию
      dockerfile: Dockerfile.admin  # Указываем какой Dockerfile использовать
    container_name: marzban-admin-bot  # Имя контейнера
    restart: unless-stopped  # Автоперезапуск при падении
    environment:
      - TZ=Europe/Moscow
    volumes:
      - broadcast-data:/app/broadcasts  # Общая папка для рассылок
    env_file:
      - .env  # Используем переменные из .env файла

  # Сервис для клиент-бота
  client-bot:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: marzban-client-bot
    restart: unless-stopped
    environment:
      - TZ=Europe/Moscow
    volumes:
      - broadcast-data:/app/broadcasts  # Та же папка что и у admin-bot
    env_file:
      - .env
    depends_on:
      - admin-bot  # Запускается после admin-bot

# Определяем volumes (тома данных)
volumes:
  broadcast-data:  # Именованный volume для рассылок